### ISSUE TITLE
cdn.mathjax.org has been retired / gorilla-repl 0.4.1

### ISSUE THREAD

**Issue by diehlj** [JonyEpsilon/lein-gorilla#11]
The bug https://github.com/JonyEpsilon/gorilla-repl/issues/269 has been fixed in 0.4.1 but lein-gorilla is still using 0.4.0. Could you put gorilla-repl 0.4.1 on clojars and make lein-gorilla use it?

(PS: https://github.com/JonyEpsilon/gorilla-repl-viewer also still has the wrong cdn.mathjax.org address for mathjax in view.html and document.html).

**Comment by benfb** [comment]
Thanks for your work on this! I just pushed the latest release of gorilla and the Lein plugin to a different repository/fork (`org.clojars.benfb/lein-gorilla`). The code for that plugin is located here: https://github.com/benfb/lein-gorilla. Jony has been mostly inactive, but I didn't want to make code changes without his approval under his name, so I created the other repository. Please raise any issues you have there. Thanks!

The newly-released version (0.5.0) of the forked plugin should fix this. To use it, just change the `lein-gorilla "0.4.0"` plugin to `org.clojars.benfb/lein-gorilla "0.5.0"`.
